name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
        - run: |
            pip install sphinx
            pip install sphinx-book-theme
            make html
            
        - name: Commit files
          run: |
            git config --local user.name actions-user
            git config --local user.email "actions@github.com"
            if ! git diff --exit-code; then
                git add your/files/here
                git commit -am "GH Action Files added $(date)"
                git push -f origin main
            fi
